### GET generic request without params:
GET http://localhost:4000/get-meteors-data
Content-Type: application/json

###GET with all set of parameters:
GET http://localhost:4000/get-meteors-data?count=true&start_date=2024-03-04&end_date=2024-03-08&
    were_dangerous_meteors=true
Content-Type: application/json

###GET with dangerous parameter only:
GET http://localhost:4000/get-meteors-data?were_dangerous_meteors=true
Content-Type: application/json

###GET with range of dates and dangerous paramters
GET http://localhost:4000/get-meteors-data?were_dangerous_meteors=true&start_date=2024-03-04&
    end_date=2024-03-08
Content-Type: application/json

###GET with range of dates parametr only:
GET http://localhost:4000/get-meteors-data?start_date=2024-03-04&end_date=2024-03-08
Content-Type: application/json

###GET with 'count' parametr only:
GET http://localhost:4000/get-meteors-data?count=true
Content-Type: application/json

###GET with date and 'count' parametr:
GET http://localhost:4000/get-meteors-data?start_date=2024-03-04&end_date=2024-03-08&count=true
Content-Type: application/json

###POST obtain photo
POST http://localhost:4000/yep-its-post-but-get-me-photo
Content-Type: application/json
Accept-Encoding: gzip, deflate, br

{
"id": "{{$random.uuid}}",
"name": "Especto Patronum",
"user_api_key": "",
"sol": 1000,
"page": 1
}

### GET posts
GET http://localhost:4000/posts/1
Content-Type: application/json